# Generated by Django 4.1 on 2022-08-27 10:51

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='rating.png', upload_to=blog.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Publish'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
